# Папка с proto-файлами
PROTO_DIR := proto/file_uploader

# Имя proto-файла
PROTO_FILE := $(PROTO_DIR)/file_uploader.proto

# Папка для генерируемых Go файлов
OUT_DIR := ./gen/go/file_uploader

# Цель по умолчанию для генерации Go файлов
all: generate

# Создаем выходную директорию, если ее нет
$(OUT_DIR):
	mkdir -p $(OUT_DIR)

# Правило для генерации Go файлов из proto
generate: $(OUT_DIR)
	protoc --go_out=$(OUT_DIR) --go-grpc_out=$(OUT_DIR) $(PROTO_FILE)

# Очистка сгенерированных файлов
clean:
	rm -f $(OUT_DIR)/*.go

# Перегенерация, если .proto изменены

.PHONY: all generate clean


.PHONY: all generate clean